### ISSUE TITLE
Duplicated class constants causing errors

### ISSUE THREAD

**Issue by markross** [klaviyo/klaviyo-api-php#14]
There are a whole load of duplicated class constants here https://github.com/klaviyo/klaviyo-api-php/blob/main/lib/Model/MetricAggregateQueryAsSubResourceAttributes.php#L268

This is causing our build to fail. Could this be fixed?

**Comment by jon-batscha** [comment]
Hey, apologies for the delay in getting back to you, we recently updated this SDK off a new spec, can you let me know if this resolved your issue?
