### ISSUE TITLE
Array to String Conversion - createListsRelationships()

### ISSUE THREAD

**Issue by treetop1500** [klaviyo/klaviyo-api-php#27]
Experiencing an Array to String Conversion error when using the createListsRelationships method of the List API.

The controller code that is leading to the error looks like this:

```
$subscriber_add_body = ['data'=>['type'=>'profile','id'=>$subscriber_id]];
$klaviyo->Lists->createListRelationships($_ENV['KLAVIYO_LIST_ID'], 'profiles', $subscriber_add_body);
```
($subscriber_id is a string)
(The Klaviyo List Id ENV var is a string)

Perhaps I'm formatting the body incorrectly however this code used to work for us, but no longer does.  I'm not sure when it began to fail unfortunately, perhaps after an update, but I was just made aware of it.

The error is as follows:

```
[DefaultController.php](_profiler/open?file=src/Controller/DefaultController.php&line=541#line541) on line 541:
ErrorException {#2710 ▼
  #message: "Warning: Array to string conversion"
  #code: 0
  #file: "[/vendor/klaviyo/api/lib/API/ListsApi.php](_profiler/open?file=vendor/klaviyo/api/lib/API/ListsApi.php&line=724#line724)"
  #line: 724
  #severity: E_WARNING
  }
}
```

**Comment by jon-batscha** [comment]
Hey, thanks for reaching out!


I see what the issue is. In `$subscriber_add_body`, `data` should be an array of objects, as opposed to a single object. If 
you update`$subscriber_add_body` as follows, it should work.

```php
$subscriber_add_body = ['data'=>[['type'=>'profile','id'=>$subscriber_id]]];
```

Please reach out if you run into any further issues, we're working hard on making our developer experience more intuitive, and this kind of feedback is super helpful in guiding our efforts.


Cheers!
Jon

**Comment by treetop1500** [comment]
Thanks for the reply. I implemented the suggested change and now receive the following error:

```
[DefaultController.php](/_profiler/open?file=src/Controller/DefaultController.php&line=1060#line1060) on line 1060:
ErrorException {#4291 ▼
  #message: "Warning: Array to string conversion"
  #code: 0
  #file: "[/vendor/klaviyo/api/lib/API/ListsApi.php](https://hoyt.test/_profiler/open?file=vendor/klaviyo/api/lib/API/ListsApi.php&line=724#line724)"
  #line: 724
  #severity: E_WARNING
```

I am using the suggested code from above:

```
$subscriber_add_body = ['data'=>[['type'=>'profile','id'=>$subscriber_id]]];
$klaviyo->Lists->createListRelationships($_ENV['KLAVIYO_LIST_ID'], 'profiles', $subscriber_add_body);
```

Thanks!
