### ISSUE TITLE
$consent variable reseted after double opt-in subscription?

### ISSUE THREAD

**Issue by asiksami** [klaviyo/klaviyo-api-php#31]
Upgrading from Klaviyo's PHP v1.2 API to v5.1. At our webstore we have page for marketing consents where user can select Klaviyo's global `$consent` variable values: `email, web, sms, directmail and mobile`. Looks like these are now saved under Klaviyo's `Profile['attributes']['properties']['$consent']` and are there after save (Profile -> Patch).

Now if all these consents are selected and user only unsubscribes from the email through web store - like newsletter (API: `profile-subscription-bulk-delete-jobs`) - and then later resubscribes back using double-opt-in (API: `profile-subscription-bulk-create-job`), `$consent` variable looses all values but `email` and/or `sms` depending on if phone number was set.

Is this normal behaviour? Or I'm missing some variables?

**Comment by asiksami** [comment]
Hi @jon-batscha! Did you find anything unordinary? If you can confirm that this as a "bug" and that willI be fixed? Or it's more a "property like" that it stays this way? I can then go on with this information.

**Comment by jon-batscha** [comment]
Hey! 

This is what I heard back from our support engineers:

> Hey Jonathan, yes I believe it is expected that the profile will be unsubscribed from all sources since the profile-subscription-bulk-delete-jobs request removes and unsubscribes the profile from the provided list(s).  They may be able to only unsubscribe the profile from the email list to have them unsubscribed from only email but I'm not certain that would work - probably have to take a look at the specific unsubscribe request they're sending.

I recommend reaching out to our support or partnerships team here for further clarification: https://www.klaviyo.com/contact-us
