### ISSUE TITLE
Add unit tests and code coverage checks.

### ISSUE THREAD

**Issue by chrishalbert** [klaviyo/klaviyo-api-php#39]
While reviewing a ticket, I was curious to see what types of test cases were covered based on the existing logic. In doing so, I noticed that there aren't any tests associated to the existing code. Is this repository being autogenerated in a way that is being tested outside this codebase? I think adding tests would be very valuable.

**Comment by jon-batscha** [comment]
Hey Chris,


Great question! 

The SDK is being auto-generated using openapi-generator + some of our customizations on top.

We have a private test suite we run locally, that doesn't ship with the package, but i'll make a note of updating our test suite so it's shareable.

Thanks again for the valuable feedback, don't hesitate to reach out if you run into any further questions.


Cheers!
Jon
