### ISSUE TITLE
Can't install on Laravel6

### ISSUE THREAD

**Issue by Ajay-Bacancy** [klaviyo/klaviyo-api-php#4]
I’m trying to integrate klaviyo/api on my laravel 6 application but it show an error for like this. I can’t upgrate the guzzle because it satisfied by other package.

![image](https://user-images.githubusercontent.com/81755827/208879235-8a5b57fe-059f-445f-a9e9-52303ad5cb5e.png)

**Comment by jon-batscha** [comment]
Hey,

Apologies for the delay, we don't currently have plans to support older versions of guzzle from before 7.3. That said, this feedback is very important to us, and we will make note of it in our backlog.

Cheers,
Jon
