### ISSUE TITLE
missing SDK equivalent for v2 endpoint people/exchange

### ISSUE THREAD

**Issue by gnikolov-sms** [klaviyo/klaviyo-api-php#57]
how can I replace **v2 people/exchange** - https://developers.klaviyo.com/en/v1-2/reference/exchange 
via sdk?

**Comment by Ian-Montgomery-Klaviyo** [comment]
You can recreate this behavior by using the `getProfiles` `$filter` property.

 Specifically if you use this filter string `"equals(_kx,\"{kx_token}\")"` and swap `{kx_token}` with your token.

To read more about this check out our migration [endpoint comparison document](https://developers.klaviyo.com/en/docs/apis_comparison_chart).
