### ISSUE TITLE
Syntax error in Webhooks API

### ISSUE THREAD

**Issue by Haggai-Mac** [klaviyo/klaviyo-api-php#60]
Hi!

PHP-Version > 8.0
Klaviyo SDK 9.0.0

Code to reproduce:

```
$klaviyo = new KlaviyoAPI(
    'YOUR_KEY',
    $num_entries = 3,
    $wait_seconds = 3
);

/**
 * @type MetricsApi $metrics
 */
$metrics = $klaviyo->Metrics;

try {
    $response = $metrics->getMetrics();
    echo json_encode($response);
} catch (ApiException $e) {
    echo $e->getCode() . ' ' . $e->getMessage();
}
```

Results in:

`syntax error, unexpected token ",", expecting variable`

The Webhooks API has a syntax error in lines 1503, 1505, 1519, 1521, 1685, 1687, 1704, 1707, and 1757. This is causing the whole SDK to fail.

**Comment by Ian-Montgomery-Klaviyo** [comment]
There was an error in the release, a patch will be out shortly.

**Comment by Ian-Montgomery-Klaviyo** [comment]
9.0.1 hotifix is out, A follow up patch to improve webhook topics will follow.

**Comment by Ian-Montgomery-Klaviyo** [comment]
9.0.1 hotfix is now out. A follow up patch will come out with improvements to webhook topics
