### ISSUE TITLE
createOrUpdateProfile does not work if you include email and phone number for profile

### ISSUE THREAD

**Issue by southcoast-matt** [klaviyo/klaviyo-api-php#63]
If a profile exists with a valid email and phone, any subsequent call to createOrUpdateProfile that also contains the email and phone again returns duplicated error:

$reponse = $klaviyo->Profiles->createOrUpdateProfile($request);
"status":409,"code":"duplicate_profile","title":"Conflict.","detail":"A profile already exists with one of these identifiers."

Surely it should simply update the existing profile?

If I exclude the the phone number in the request the profile is updated as expected.

**Comment by southcoast-matt** [comment]
OK, so even more odd, if I save the klaviyo profile id in my db and call upateProfile, if I include the email AND phone number it again returns 409 duplicate error?? This is surely not intended? It makes it impossible to do an update to a profile?

$reponse = $klaviyo->Profiles->updateProfile($contact['klaviyo_id'], $request);

"status":409,"code":"duplicate_profile","title":"Conflict.","detail":"A profile already exists with one of these identifiers.

My client has various ways profiles are added - So my API calls might be for profiles that were ceated elsewhere. Do you expect me to call getProfiles with a filter before every update/create call to check if the email / phone already has a profle? If so then the naming of this method should be changed as it doesn;t do what it says!
createOrUpdateProfile

**Comment by nat-klaviyo** [comment]
Hi, this seems like an issue with the API rather than the SDK - could you submit a [support ticket](https://www.klaviyo.com/support)?

**Comment by southcoast-matt** [comment]
Hi

After hours of wasted time I figured it out from a 3rd party forum. My clients system has unique emails but not unique phone (pretty common I would imagine), but klaviyo records MUST have both as unique. 

To test I am pushing from a dev server with data using various emails that come to me, but many with my mobile number. If you run any method that tries to update that includes email and phone in the request (even if you include the unique klaviyo_id, if there is another record with the same phone number [but different email] the api call will always fail. 

You need to make this VERY clear in your API docs as it doesn't mention this anywhere. My temp fix - as the client not currenl;y using you for sms, is to not bother sending phone number in any of our calls. I will figure out how to cope with duplicate phones another day! Not ideal but simplest solution would be to create 2 seperate records in klaviyo - 1 email, 1 sms

For my piece of mind, can you confirm that this new api is production ready and the version to use? The github repo seems earily quiet in terms of issues - making me think most people are still using the old version. Much of your docs still link internally to pages that have 'depreciated' warning at the top, even when following links from new API docs.

**Comment by cpcurtis1218** [comment]
Hi there, I wanted to note that as of the 2024-10-15 API revision there has been an update that allows multiple duplicate phone number profiles with different emails in Klaviyo.  You can find the latest API changelog [here](https://developers.klaviyo.com/en/docs/changelog_).
