### ISSUE TITLE
Missing price property in `CatalogItemCreateQueryAsSubResourceAttributes` model

### ISSUE THREAD

**Issue by lusimeon** [klaviyo/klaviyo-api-php#8]
Hi,

I don't see `price` property in mapped properties of [CatalogItemCreateQueryAsSubResourceAttributes](https://github.com/klaviyo/klaviyo-api-php/blob/main/lib/Model/CatalogItemCreateQueryAsSubResourceAttributes.php) model. _It seems it does not exist in node and python Klaviyo libraries neither_

However, this attribute exists in Klaviyo catalog product view.
Is this attribute is missing from this repo? Or is it an abandoned attribute in favor of variant price?
![klaviyo_product_view](https://user-images.githubusercontent.com/5418329/220597888-de545ad0-cb12-4ad4-b37d-4402d0e37663.jpeg)

**Comment by jon-batscha** [comment]
Hey Lucas,

Great catch! And very timely. We just shipped a fix for this to our underlying spec (so you can now see this reflected in our docs): https://developers.klaviyo.com/en/reference/create_catalog_item

Now the next step is for us to roll out this change to the SDKs, which we plan to get done within the next day. Keep a look out for the upcoming release here.

Thanks again for the detailed feedback, definitely let us know if you run up against any other issues.

Cheers,
Jon
